# Bateria
CONFIG_ZMK_BATTERY_REPORTING=y

# Bluetooth
CONFIG_BT_CTLR_TX_PWR_PLUS_8=y

# Deep sleep após 15 minutos de inatividade
CONFIG_ZMK_SLEEP=y
CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=900000

# Sem RGB (economia de bateria)
CONFIG_ZMK_RGB_UNDERGLOW=n

# OLED desabilitado (não vai usar)
CONFIG_ZMK_DISPLAY=n
